name: heart-disease-env

channels:
  - conda-forge

dependencies:
  - python=3.13
  - pip

  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - scipy
      - joblib